### ISSUE TITLE
GUI frozen while running multiple process ?

### ISSUE THREAD

**Issue by manhntm3** [pieper/SlicerProcesses#6]
If I put a time.sleep(5) in a processing input output function like this:

    def prepareProcessInput(self):
        input = {}
        input['array'] = slicer.util.arrayFromVolume(self.volumeNode)
        input['spacing'] = self.volumeNode.GetSpacing()
        input['dimensions'] = self.volumeNode.GetImageData().GetDimensions()
        input['type'] = self.volumeNode.GetImageData().GetScalarType()
        input['radius'] = self.radius
        time.sleep(5)
        return pickle.dumps(input)
When it performs the test, the GUI is frozen and inaccessible. Is there any way to change GUI when waiting for processing in background ?

**Comment by pieper** [comment]
The `prepare` step happens in the main thread of the Slicer process, so yes, this will freeze the application.  You need to put code like that in your `ProcessScript`, which runs in a different OS process from the main application.

For example:

https://github.com/pieper/SlicerProcesses/blob/master/Processes/Resources/ProcessScripts/modelFilter.slicer.py
